const drivers = [
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },
  { id: 1, name: "Michael Johnson", available: true, location: "Point A", car: { plate: "ABC-1234", model: "Camry", make: "Toyota", color: "Black", year: 2020 } },
  { id: 2, name: "Sarah Lee", available: true, location: "Point B", car: { plate: "XYZ-5678", model: "Civic", make: "Honda", color: "White", year: 2022 } },
  { id: 3, name: "David Smith", available: true, location: "Point C", car: { plate: "LMN-9876", model: "Model 3", make: "Tesla", color: "Red", year: 2023 } },
  { id: 4, name: "Emily Davis", available: true, location: "Point D", car: { plate: "QWE-4321", model: "Accord", make: "Honda", color: "Blue", year: 2021 } },

];

module.exports = { drivers };